name: Update Database

on:
  schedule:
    - cron: '0 0 */5 * *'  # Runs at 00:00 every 5 days
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed for pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download source database
        run: |
          wget -O bag-light.gpkg https://service.pdok.nl/lv/bag/atom/downloads/bag-light.gpkg

      - name: Install dependencies
        run: go mod download

      - name: Run conversion
        run: |
          go run main.go
          go run main.go -optimize

      - name: Upload database
        id: upload
        run: |
          chmod +x scripts/upload.sh
          DOWNLOAD_URL=$(./scripts/upload.sh converted.db)
          echo "download_url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT

      - name: Update files
        run: |
          # Write only the URL to text file
          echo "${{ steps.upload.outputs.download_url }}" > download_url.txt
          
          # Commit both files
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md download_url.txt
          git commit -m "Update database download link [skip ci]" || exit 0
          git push